<?xml version="1.0"?>

<robot name="basketbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find basketbot)/urdf/basketbot.gazebo" />
  
  <!--  VARIABLES -->
  <xacro:property name="chassis_length" value="1.1" />
  <xacro:property name="chassis_width" value="0.84" />
  <xacro:property name="chassis_height" value="0.8" />

  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="wheel_radius" value="0.075" />
  <xacro:property name="wheel_mass" value="0.25" />
  <xacro:property name="wheel_x_offset" value="0.35" />
  <xacro:property name="wheel_y_offset" value="${(chassis_width/2) + (wheel_length/2)+0.01}" />
  <xacro:property name="wheel_z_offset" value="-${(wheel_radius)}" /> <!-- -0.355 -->
  <xacro:property name="wheel_inertia" value="0.005" />
  <xacro:property name="wheel_kp" value="1000000.0" />
  <xacro:property name="wheel_kd" value="100.0" />
  <xacro:property name="wheel_mu1" value="1" />
  <xacro:property name="wheel_mu2" value="1" />
  <xacro:property name="wheel_slip1" value="0.5" />
  <xacro:property name="wheel_slip2" value="0" />

  <!-- ROOT LINK and ROBOT CHASSIS -->
  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint" />
    <child link="chassis" />
  </joint>
  
  <link name="chassis">
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="10.0" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia
        ixx="0.1" ixy="0" ixz="0"
        iyy="0.1" iyz="0"
        izz="0.1"
      />
    </inertial>

    <collision name="collision">
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
    </collision>

    <visual name="chassis_visual">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <!--<box size="${chassis_length} ${chassis_width} ${chassis_height}" />-->
        <mesh filename="package://basketbot/meshes/BasketBotModel.dae" />
      </geometry>
    </visual>
  </link>
  
  <!--  WHEELS  -->
  <joint type="continuous" name="wheel_left_front_joint">
    <origin xyz="${wheel_x_offset} ${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="wheel_left_front"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" />
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="0.1" friction="1.0"/>
  </joint>
  <joint type="continuous" name="wheel_left_rear_joint">
    <origin xyz="-${wheel_x_offset} ${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="wheel_left_rear"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" />
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="0.1" friction="1.0"/>
  </joint>
  <joint type="continuous" name="wheel_right_front_joint">
    <origin xyz="${wheel_x_offset} -${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="wheel_right_front"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" />
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="0.1" friction="1.0"/>
  </joint>
  <joint type="continuous" name="wheel_right_rear_joint">
    <origin xyz="-${wheel_x_offset} -${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="wheel_right_rear"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" />
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="0.1" friction="1.0"/>
  </joint>


  <link name="wheel_left_front">
    <visual name="wheel_left_front_visual">
      <origin xyz="0.0 0 -${wheel_radius}" rpy="0 0 ${pi}" />
      <geometry>
        <mesh filename="package://basketbot/meshes/wheel.dae" />
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
    </visual>
    <collision name="wheel_left_front_collision">
      <origin xyz="0.0 0 0" rpy="0 ${pi/2} ${pi/2}" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
      <surface>
        <friction>
          <fdir1>1 0 0</fdir1>
          <kp>${wheel_kp}</kp>
          <kd>${wheel_kd}</kd>
          <mu>${wheel_mu1}</mu>
          <mu2>${wheel_mu2}</mu2>
          <slip1>${wheel_slip1}</slip1>
          <slip2>${wheel_slip2}</slip2>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0.0 0 0" rpy="0 ${pi/2} ${pi/2}" />
      <inertia
        ixx="${wheel_inertia}" ixy="0" ixz="0"
        iyy="${wheel_inertia}" iyz="0"
        izz="${wheel_inertia}"
      />
    </inertial>
  </link>

  <link name="wheel_left_rear">
    <visual name="wheel_left_rear_visual">
      <origin xyz="0.0 0 -${wheel_radius}" rpy="0 0 ${pi}" />
      <geometry>
        <mesh filename="package://basketbot/meshes/wheel.dae" />
      </geometry>
    </visual>

    <collision name="wheel_left_rear_collision">
      <origin xyz="0.0 0 0" rpy="0 ${pi/2} ${pi/2}" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
      <surface>
        <friction>
          <fdir1>1 0 0</fdir1>
          <kp>${wheel_kp}</kp>
          <kd>${wheel_kd}</kd>
          <mu>${wheel_mu1}</mu>
          <mu2>${wheel_mu2}</mu2>
          <slip1>${wheel_slip1}</slip1>
          <slip2>${wheel_slip2}</slip2>
        </friction>
      </surface>
    </collision>

    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0.0 0 0" rpy="0 ${pi/2} ${pi/2}" />
      <inertia
        ixx="${wheel_inertia}" ixy="0" ixz="0"
        iyy="${wheel_inertia}" iyz="0"
        izz="${wheel_inertia}"
      />
    </inertial>
  </link>

  <link name="wheel_right_front">
    <visual name="wheel_right_front_visual">
      <origin xyz="0.0 0 -${wheel_radius}" rpy="0 0 ${pi*2}" />
      <geometry>
      <mesh filename="package://basketbot/meshes/wheel.dae" />
      </geometry>
    </visual>

    <collision name="wheel_right_front_collision">
      <origin xyz="0.0 0 0" rpy="0 ${pi/2} ${pi/2}" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
      <surface>
        <friction>
          <fdir1>1 0 0</fdir1>
          <kp>${wheel_kp}</kp> 
          <kd>${wheel_kd}</kd>
          <mu>${wheel_mu1}</mu>
          <mu2>${wheel_mu2}</mu2>
          <slip1>${wheel_slip1}</slip1>
          <slip2>${wheel_slip2}</slip2>
        </friction>
      </surface>
    </collision>

    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0.0 0 0" rpy="0 ${pi/2} ${pi/2}" />
      <inertia
        ixx="${wheel_inertia}" ixy="0" ixz="0"
        iyy="${wheel_inertia}" iyz="0"
        izz="${wheel_inertia}"
      />
    </inertial>
  </link>

  <link name="wheel_right_rear">
    <visual name="wheel_right_rear_visual">
      <origin xyz="0.0 0 -${wheel_radius}" rpy="0 0 ${pi*2}" />
      <geometry>
        <mesh filename="package://basketbot/meshes/wheel.dae" />
      </geometry>
    </visual>

    <collision name="wheel_right_rear_collision">
      <origin xyz="0.0 0 0" rpy="0 ${pi/2} ${pi/2}" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
      <surface>
        <friction>
          <fdir1>1 0 0</fdir1>
          <kp>${wheel_kp}</kp>
          <kd>${wheel_kd}</kd>
          <mu>${wheel_mu1}</mu>
          <mu2>${wheel_mu2}</mu2>
          <slip1>${wheel_slip1}</slip1>
          <slip2>${wheel_slip2}</slip2>
        </friction>
      </surface>
    </collision>

    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0.0 0 0" rpy="0 ${pi/2} ${pi/2}" />
      <inertia
        ixx="${wheel_inertia}" ixy="0" ixz="0"
        iyy="${wheel_inertia}" iyz="0"
        izz="${wheel_inertia}"
      />
    </inertial>
  </link>

  <!-- SENSORS  -->
  <joint type="fixed" name="camera_joint">
    <origin xyz="0.525 0 0.2" rpy="0 0 0" />
    <child link="camera" />
    <parent link="chassis" />
    <axis xyz="0 1 0" />
  </joint>
  <link name="camera">
    <visual name="camera_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05" />
      </geometry>
    </visual>

    <collision name="camera_collision">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 0.05" />
      </geometry>
    </collision>

    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <box_inertia m="0.1" x="0.05" y="0.05" z="0.05" />
      <inertia
        ixx="1e-6" ixy="0" ixz="0"
        iyy="1e-6" iyz="0"
        izz="1e-6"
      />
    </inertial>
  </link>

  <joint type="fixed" name="camera_optical_joint">
    <origin xyz="0 0 0" rpy="-${pi/2} 0 -${pi/2}" />
    <child link="camera_link_optical" />
    <parent link="camera" />
    <!--<axis xyz="0 1 0" />-->
  </joint>
  <link name="camera_link_optical">
    <visual name="camera_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05" />
      </geometry>
    </visual>

    <collision name="camera_collision">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 0.05" />
      </geometry>
    </collision>

    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <box_inertia m="0.1" x="0.05" y="0.05" z="0.05" />
      <inertia
        ixx="1e-6" ixy="0" ixz="0"
        iyy="1e-6" iyz="0"
        izz="1e-6"
      />
    </inertial>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="0.525 0 0.25" rpy="0 0 0" />
    <child link="hokuyo" />
    <parent link="chassis" />
    <axis xyz="0 1 0" />
  </joint>
  <link name="hokuyo">
    <visual name="hokuyo_visual">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://basketbot/meshes/hokuyo.dae" />
      </geometry>
    </visual>

    <collision name="hokuyo_collision">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.1 0.1 0.1" />
      </geometry>
    </collision>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia
        ixx="1e-6" ixy="0" ixz="0"
        iyy="1e-6" iyz="0"
        izz="1e-6"
      />
    </inertial>
  </link>

  <gazebo reference="camera">
    <material>Gazebo/Red</material>
  </gazebo>
</robot>